apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - image: nginx
    name: nginx-container
  tolerations:
  - key: "app"
    value: "blue"
    effect: NoSchedule
    operator: "Equal"