apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app : elasticsearch
  name:  elasticsearch
  namespace : kube-system
spec:
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: k8s.gcr.io/fluentd-elasticsearch:1.20    
  selector:
    matchLabels:
      app: elasticsearch
    